fix(ci): debug issues with github token (#98)
* fix(workflows): fix bug in github cli login and temporarily disable service deployment

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,6 +10,48 @@ permissions:
   pull-requests: write  # This allows the workflow to comment on PRs
 
 jobs:
+  debug-gh-token:
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      issues: write
+    steps:
+      - name: Check-out Code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0  # Ensure full checkout
+      - name: Debug Git Auth
+        run: |
+          # Temporarily unset GITHUB_TOKEN
+          GITHUB_TOKEN_BACKUP=$GITHUB_TOKEN
+          unset GITHUB_TOKEN
+          
+          echo "Authenticating with PAT..."
+          gh auth login --with-token <<< "$GH_ACTIONS_PAT"
+          
+          echo "Verifying GitHub authentication..."
+          gh auth status
+          
+          ENV=dev
+          echo "> Attempting to access $ENV environment variables..."
+
+          echo "Listing variables for $ENV:"
+          if ! VARS=$(gh variable list -e $ENV 2>&1); then
+            echo "Failed to list variables. Error:"
+            echo "$VARS"
+            echo "Attempting to get repository details..."
+            gh api repos/$GITHUB_REPOSITORY || echo "Failed to access repo API"
+            echo "Attempting to list environments..."
+            gh api repos/$GITHUB_REPOSITORY/environments || echo "Failed to list environments"
+          else
+            echo "$VARS"
+          fi
+          
+          # Restore GITHUB_TOKEN if needed for other operations
+          export GITHUB_TOKEN=$GITHUB_TOKEN_BACKUP
+        env:
+          GH_ACTIONS_PAT: ${{ secrets.GH_ACTIONS_PAT }}
+        
   check-changes:
     name: Check Changes
     runs-on: ubuntu-latest
diff --git a/.github/workflows/deployment-dev-staging.yml b/.github/workflows/deployment-dev-staging.yml
--- a/.github/workflows/deployment-dev-staging.yml
+++ b/.github/workflows/deployment-dev-staging.yml
@@ -91,22 +91,18 @@ jobs:
       - name: Build and Deploy to Dev & Staging
         uses: devcontainers/ci@v0.3
         env:
-          GH_TOKEN: ${{ secrets.GH_REPO_PAT }}
+          GH_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
         with:
           runCmd: |
             set -e
 
-            echo "GitHub CLI version:"
-            gh --version
-
-            echo "Authenticating with GitHub..."
-            export GH_TOKEN=${{ secrets.GH_REPO_PAT }}
-            gh auth login --with-token <<< $GH_TOKEN
-            if [ $? -ne 0 ]; then
-              echo "Failed to authenticate with GitHub CLI"
-              exit 1
-            fi
-
+            # Temporarily unset GITHUB_TOKEN, it does not have all the required permissions by default
+            GITHUB_TOKEN_BACKUP=$GITHUB_TOKEN
+            unset GITHUB_TOKEN
+            
+            echo ">> Authenticating with GH_ACTIONS_PAT..."
+            gh auth login --with-token <<< "$GH_ACTIONS_PAT"
+            
             echo "Verifying GitHub authentication..."
             gh auth status
             if [ $? -ne 0 ]; then
@@ -114,43 +110,61 @@ jobs:
               exit 1
             fi
 
-            echo "Installing and building with Poetry..."
-            poetry run install-all
-            poetry run build-all
-
             deploy_to_env() {
               local ENV=$1
-              echo "> Deploying to $ENV environment..."
-
-              echo "Listing variables for $ENV:"
-              VARS=$(gh variable list -e $ENV)
-              if [ $? -ne 0 ]; then
-                echo "Failed to list variables for $ENV environment"
-                return 1
+              ENV=dev
+              
+              echo ">> Getting variables for $ENV environment:"
+              if ! VARS=$(gh variable list -e $ENV 2>&1); then
+                echo "Failed to list variables. Error:"
+                echo "$VARS"
+                echo "Attempting to get repository details..."
+                gh api repos/$GITHUB_REPOSITORY || echo "Failed to access repo API"
+                echo "Attempting to list environments..."
+                gh api repos/$GITHUB_REPOSITORY/environments || echo "Failed to list environments"
+              else
+                echo "$VARS"
               fi
-              echo "$VARS"
 
               AWS_ACCOUNT_ID=$(echo "$VARS" | grep AWS_ACCOUNT_ID | awk '{print $2}')
-              if [ -z "$AWS_ACCOUNT_ID" ]; then
-                echo "Failed to retrieve AWS_ACCOUNT_ID for $ENV environment"
-                return 1
-              fi
-
               AWS_PRIMARY_REGION=$(echo "$VARS" | grep AWS_PRIMARY_REGION | awk '{print $2}')
-              if [ -z "$AWS_PRIMARY_REGION" ]; then
-                echo "Failed to retrieve AWS_PRIMARY_REGION for $ENV environment"
+              AWS_GITHUB_ACTIONS_ROLE=$(echo "$VARS" | grep AWS_GITHUB_ACTIONS_ROLE | awk '{print $2}')
+
+              if [ -z "$AWS_ACCOUNT_ID" ] || [ -z "$AWS_PRIMARY_REGION" ] || [ -z "$AWS_GITHUB_ACTIONS_ROLE" ]; then
+                echo "Failed to retrieve necessary AWS variables for $ENV environment"
                 return 1
               fi
 
               echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"
               echo "AWS_PRIMARY_REGION: $AWS_PRIMARY_REGION"
+              echo "AWS_GITHUB_ACTIONS_ROLE: $AWS_GITHUB_ACTIONS_ROLE"
+
+              echo ">> Configuring AWS credentials for $ENV..."
+              # Similarly to aws-actions/configure-aws-credentials to set up credentials
+              aws-actions-configure-aws-credentials \
+                --role-to-assume "$AWS_GITHUB_ACTIONS_ROLE" \
+                --role-session-name "GithubWorkflow-DeployServices-$ENV" \
+                --aws-region "$AWS_PRIMARY_REGION"
+
+              echo "Verifying AWS authentication for $ENV..."
+              aws sts get-caller-identity
+
+              echo ">> Deploying to $ENV environment..."
+              poetry run install-all
+              poetry run build-all
 
               chmod +x .github/scripts/sam-build-and-deploy-services.sh
-              .github/scripts/sam-build-and-deploy-services.sh $ENV $AWS_ACCOUNT_ID $AWS_PRIMARY_REGION
+              
+              # Temporarily disable deployment
+              # .github/scripts/sam-build-and-deploy-services.sh $ENV $AWS_ACCOUNT_ID $AWS_PRIMARY_REGION
             }
 
             deploy_to_env "dev" || exit 1
             deploy_to_env "staging" || exit 1
+
+            # Restore GITHUB_TOKEN if needed for other operations
+            export GITHUB_TOKEN=$GITHUB_TOKEN_BACKUP
+
 
 # name: Deploy to Dev & Staging
 
