debug deployment - adding check0changes jb and deploy configs separately

diff --git a/.github/workflows/debug-aws-login.yml b/.github/workflows/debug-aws-login.yml
--- a/.github/workflows/debug-aws-login.yml
+++ b/.github/workflows/debug-aws-login.yml
@@ -1,4 +1,4 @@
-name: Debug AWS Login
+name: Debug Deployment
 
 on:
   pull_request:
@@ -11,8 +11,101 @@ permissions:
   pull-requests: write  # Allows the workflow to comment on PRs
 
 jobs:
-  debug-gh-token:
+  check-changes:
+    name: Check Changes
     runs-on: ubuntu-latest
+    outputs:
+      terraform_changed: ${{ steps.check.outputs.terraform_changed }}
+      code_changed: ${{ steps.check.outputs.code_changed }}
+      services_with_config_changed: ${{ steps.check.outputs.services_with_config_changed }}
+  
+    steps:
+      - name: Check-out Code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0  # Ensure full checkout
+
+      - name: Check for Terraform & Code Changes
+        id: check
+        run: |
+          echo "Processing Push Event"
+          BASE_SHA=${{ github.event.before }}
+          HEAD_SHA=${{ github.event.after }}
+
+          git diff --name-only $BASE_SHA $HEAD_SHA > changed_files.txt
+          
+          echo "Changed files:"
+          cat changed_files.txt
+          
+          echo "Checking for Terraform changes..."
+          if grep -q "^infra/terraform/.*\.(tf|tfvars|lock\.hcl)$" changed_files.txt; then
+            echo "terraform_changed=true" >> $GITHUB_OUTPUT
+            echo "Matching Terraform files:"
+            grep "^infra/terraform/" changed_files.txt
+          else
+            echo "terraform_changed=false" >> $GITHUB_OUTPUT
+          fi
+          
+          echo "Checking for Code changes..."
+          if grep -qE "^(services|packages)/.*\.(py|toml|ya?ml|lock)$" changed_files.txt; then
+             echo "code_changed=true" >> $GITHUB_OUTPUT
+             echo "Matching Code files:"
+             grep -E "^services/|^packages/" changed_files.txt
+          else
+             echo "code_changed=false" >> $GITHUB_OUTPUT
+          fi
+
+          echo "Checking for Service Config changes..."
+          services_with_config_changed=$(grep "^services/.*/config/" changed_files.txt | cut -d'/' -f2 | sort -u | jq -R -s -c 'split("\n")[:-1]')
+          echo "services_with_config_changed=$services_with_config_changed" >> $GITHUB_OUTPUT
+
+      - name: Display check-changes Output
+        run: |
+          echo "Terraform changed: ${{ steps.check.outputs.terraform_changed }}"
+          echo "Code changed: ${{ steps.check.outputs.code_changed }}"
+          echo "Services with Config changed: ${{ steps.check.outputs.services_with_config_changed }}"
+
+  deploy-service-config:
+    name: Deploy Service Configurations
+    needs: [check-changes]
+    if: needs.check-changes.outputs.services_with_config_changed != '[]'
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        environment: [dev, staging]
+    steps:
+      - name: Check-out Code
+        uses: actions/checkout@v4
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
+          role-session-name: GithubWorkflow-ServiceConfigDeployment-${{ matrix.environment }}
+          aws-region: ${{ vars.AWS_PRIMARY_REGION }}
+          role-duration-seconds: 900
+          role-skip-session-tagging: true
+
+      - name: Deploy Service Configurations
+        run: |
+          services_array=$(echo '${{ needs.check-changes.outputs.services_with_config_changed }}' | jq -r '.[]')
+
+          chmod +x .github/scripts/deploy-service-configuration.sh
+
+          for service in $services_array; do
+            echo "Deploying configuration for service: $service"
+            if ! .github/scripts/deploy-service-configuration.sh --service-name "$service" --stage ${{ matrix.environment }} --region ${{ vars.AWS_PRIMARY_REGION }} --platform AWS; then
+              echo "Error: Failed to deploy configuratio for service $service on environment ${{ matrix.environment }} in region ${{ vars.AWS_PRIMARY_REGION }} . Aborting."
+              return 1
+            fi
+          done
+
+          echo "Services' configuration deployment completed successfully!"
+  
+  deploy-services:
+    runs-on: ubuntu-latest
+    needs: [check-changes, deploy-service-config]
+    if: needs.check-changes.outputs.code_changed != '[]'
     environment: dev
     steps:
       - name: Check-out Code
@@ -25,7 +118,7 @@ jobs:
         uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
-          role-session-name: GithubWorkflow-TerraformPlan-${{ inputs.environment }}
+          role-session-name: GithubWorkflow-Deployment-dev-staging
           aws-region: ${{ vars.AWS_PRIMARY_REGION }}
           output-credentials: true
       
@@ -103,7 +196,7 @@ jobs:
               chmod +x .github/scripts/sam-build-and-deploy-services.sh 
               chmod +x .github/scripts/deploy-service-configuration.sh
 
-              if ! .github/scripts/sam-build-and-deploy-services.sh $ENV $AWS_ACCOUNT_ID $AWS_PRIMARY_REGION true ; then
+              if ! .github/scripts/sam-build-and-deploy-services.sh $ENV $AWS_ACCOUNT_ID $AWS_PRIMARY_REGION false ; then
                 echo "Deployment failed for $ENV environment"
                 return 1
               fi
