fix(deployment): troubleshoot gitub authentication + dummy change to trigger deployment

diff --git a/.github/workflows/deployment-dev-staging.yml b/.github/workflows/deployment-dev-staging.yml
--- a/.github/workflows/deployment-dev-staging.yml
+++ b/.github/workflows/deployment-dev-staging.yml
@@ -76,80 +76,80 @@ jobs:
     needs: [check-changes, deploy-infra]
     if: needs.check-changes.outputs.code_changed == 'true'
     runs-on: ubuntu-latest
-    
+
     steps:
-    - name: Check-out Code
-      uses: actions/checkout@v4
+      - name: Check-out Code
+        uses: actions/checkout@v4
 
-    - name: Set-up Devcontainer Environment Variables
-      run: |
-        echo "PWD=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
-        cp .devcontainer/.env.ci .devcontainer/.env
-        echo ".devcontainer/.env:"
-        cat .devcontainer/.env
+      - name: Set-up Devcontainer Environment Variables
+        run: |
+          echo "PWD=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
+          cp .devcontainer/.env.ci .devcontainer/.env
+          echo ".devcontainer/.env:"
+          cat .devcontainer/.env
 
-    - name: Build and Deploy to Dev & Staging
-      uses: devcontainers/ci@v0.3
-      env:
-        GH_TOKEN: ${{ secrets.GH_REPO_PAT }}
-      with:
-        runCmd: |
-          set -e
+      - name: Build and Deploy to Dev & Staging
+        uses: devcontainers/ci@v0.3
+        env:
+          GH_TOKEN: ${{ secrets.GH_REPO_PAT }}
+        with:
+          runCmd: |
+            set -e
 
-          echo "GitHub CLI version:"
-          gh --version
+            echo "GitHub CLI version:"
+            gh --version
 
-          echo "Authenticating with GitHub..."
-          echo "$GH_TOKEN" | gh auth login --with-token
-          if [ $? -ne 0 ]; then
-            echo "Failed to authenticate with GitHub CLI"
-            exit 1
-          fi
-
-          echo "Verifying GitHub authentication..."
-          gh auth status
-          if [ $? -ne 0 ]; then
-            echo "GitHub CLI is not authenticated"
-            exit 1
-          fi
-
-          echo "Installing and building with Poetry..."
-          poetry run install-all
-          poetry run build-all
-
-          deploy_to_env() {
-            local ENV=$1
-            echo "> Deploying to $ENV environment..."
-
-            echo "Listing variables for $ENV:"
-            VARS=$(gh variable list -e $ENV)
+            echo "Authenticating with GitHub..."
+            gh auth login --with-token <<< $GH_TOKEN
             if [ $? -ne 0 ]; then
-              echo "Failed to list variables for $ENV environment"
-              return 1
-            fi
-            echo "$VARS"
-
-            AWS_ACCOUNT_ID=$(echo "$VARS" | grep AWS_ACCOUNT_ID | awk '{print $2}')
-            if [ -z "$AWS_ACCOUNT_ID" ]; then
-              echo "Failed to retrieve AWS_ACCOUNT_ID for $ENV environment"
-              return 1
+              echo "Failed to authenticate with GitHub CLI"
+              exit 1
             fi
 
-            AWS_PRIMARY_REGION=$(echo "$VARS" | grep AWS_PRIMARY_REGION | awk '{print $2}')
-            if [ -z "$AWS_PRIMARY_REGION" ]; then
-              echo "Failed to retrieve AWS_PRIMARY_REGION for $ENV environment"
-              return 1
+            echo "Verifying GitHub authentication..."
+            gh auth status
+            if [ $? -ne 0 ]; then
+              echo "GitHub CLI is not authenticated"
+              exit 1
             fi
 
-            echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"
-            echo "AWS_PRIMARY_REGION: $AWS_PRIMARY_REGION"
+            echo "Installing and building with Poetry..."
+            poetry run install-all
+            poetry run build-all
 
-            chmod +x .github/scripts/sam-build-and-deploy-services.sh
-            .github/scripts/sam-build-and-deploy-services.sh $ENV $AWS_ACCOUNT_ID $AWS_PRIMARY_REGION
-          }
+            deploy_to_env() {
+              local ENV=$1
+              echo "> Deploying to $ENV environment..."
 
-          deploy_to_env "dev" || exit 1
-          deploy_to_env "staging" || exit 1
+              echo "Listing variables for $ENV:"
+              VARS=$(gh variable list -e $ENV)
+              if [ $? -ne 0 ]; then
+                echo "Failed to list variables for $ENV environment"
+                return 1
+              fi
+              echo "$VARS"
+
+              AWS_ACCOUNT_ID=$(echo "$VARS" | grep AWS_ACCOUNT_ID | awk '{print $2}')
+              if [ -z "$AWS_ACCOUNT_ID" ]; then
+                echo "Failed to retrieve AWS_ACCOUNT_ID for $ENV environment"
+                return 1
+              fi
+
+              AWS_PRIMARY_REGION=$(echo "$VARS" | grep AWS_PRIMARY_REGION | awk '{print $2}')
+              if [ -z "$AWS_PRIMARY_REGION" ]; then
+                echo "Failed to retrieve AWS_PRIMARY_REGION for $ENV environment"
+                return 1
+              fi
+
+              echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"
+              echo "AWS_PRIMARY_REGION: $AWS_PRIMARY_REGION"
+
+              chmod +x .github/scripts/sam-build-and-deploy-services.sh
+              .github/scripts/sam-build-and-deploy-services.sh $ENV $AWS_ACCOUNT_ID $AWS_PRIMARY_REGION
+            }
+
+            deploy_to_env "dev" || exit 1
+            deploy_to_env "staging" || exit 1
 
 # name: Deploy to Dev & Staging
 
