fix(deployment): troubleshoot gitub authentication + dummy change to trigger deployment

diff --git a/.github/workflows/deployment-dev-staging.yml b/.github/workflows/deployment-dev-staging.yml
--- a/.github/workflows/deployment-dev-staging.yml
+++ b/.github/workflows/deployment-dev-staging.yml
@@ -95,46 +95,55 @@ jobs:
       with:
         runCmd: |
           set -e
-          
-          # Debug information
+
           echo "GitHub CLI version:"
           gh --version
-          
-          # Use GH_TOKEN environment variable for authentication
+
           echo "Authenticating with GitHub..."
-          gh auth status || echo "Not authenticated"
-          
+          echo "$GH_TOKEN" | gh auth login --with-token
+          if [ $? -ne 0 ]; then
+            echo "Failed to authenticate with GitHub CLI"
+            exit 1
+          fi
+
           echo "Verifying GitHub authentication..."
           gh auth status
-          
+          if [ $? -ne 0 ]; then
+            echo "GitHub CLI is not authenticated"
+            exit 1
+          fi
+
           echo "Installing and building with Poetry..."
           poetry run install-all
           poetry run build-all
 
-          # Function to deploy to an environment
           deploy_to_env() {
             local ENV=$1
             echo "> Deploying to $ENV environment..."
-            
+
             echo "Listing variables for $ENV:"
             VARS=$(gh variable list -e $ENV)
+            if [ $? -ne 0 ]; then
+              echo "Failed to list variables for $ENV environment"
+              return 1
+            fi
             echo "$VARS"
-            
+
             AWS_ACCOUNT_ID=$(echo "$VARS" | grep AWS_ACCOUNT_ID | awk '{print $2}')
             if [ -z "$AWS_ACCOUNT_ID" ]; then
               echo "Failed to retrieve AWS_ACCOUNT_ID for $ENV environment"
               return 1
             fi
-            
+
             AWS_PRIMARY_REGION=$(echo "$VARS" | grep AWS_PRIMARY_REGION | awk '{print $2}')
             if [ -z "$AWS_PRIMARY_REGION" ]; then
               echo "Failed to retrieve AWS_PRIMARY_REGION for $ENV environment"
               return 1
             fi
-            
+
             echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"
             echo "AWS_PRIMARY_REGION: $AWS_PRIMARY_REGION"
-            
+
             chmod +x .github/scripts/sam-build-and-deploy-services.sh
             .github/scripts/sam-build-and-deploy-services.sh $ENV $AWS_ACCOUNT_ID $AWS_PRIMARY_REGION
           }
