use reusable workflow for service deployment

diff --git a/.github/workflows/deployment-dev-staging.yml b/.github/workflows/deployment-dev-staging.yml
--- a/.github/workflows/deployment-dev-staging.yml
+++ b/.github/workflows/deployment-dev-staging.yml
@@ -121,68 +121,79 @@ jobs:
           echo "Services' configuration deployment completed successfully!"
 
   deploy-services:
-    runs-on: ubuntu-latest
-    needs: [check-changes, deploy-service-config]
+    name: Deploy Services
+    needs: [check-changes]
     if: needs.check-changes.outputs.code_changed  == 'true'
     strategy:
       matrix:
         environment: [dev, staging]
-    environment: ${{ matrix.environment }}
-    steps:
-      - name: Check-out Code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0  # Ensure full checkout
-      
-      - name: Configure AWS credentials
-        id: aws-creds
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
-          role-session-name: GithubWorkflow-Deployment-dev-staging
-          aws-region: ${{ vars.AWS_PRIMARY_REGION }}
-          output-credentials: true
-      
-      - name: Set-up Devcontainer Environment Variables
-        run: |
-          echo "PWD=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
-          cp .devcontainer/.env.ci .devcontainer/.env
-          echo ".devcontainer/.env:"
-          cat .devcontainer/.env
+    uses: ./.github/workflows/deploy-services-reusable.yml
+    with:
+      environment: ${{ matrix.environment }}
 
-      - name: Deploy Services to ${{ matrix.environment }}
-        uses: devcontainers/ci@v0.3
-        env:
-          GH_ACTIONS_PAT: ${{ secrets.GH_ACTIONS_PAT }}
-        with:
-          cacheFrom: ghcr.io/limorl/monorepo-python-sample-devcontainer
-          push: never
-          env: |
-            AWS_REGION=${{ vars.AWS_PRIMARY_REGION }}
-            AWS_ACCOUNT_ID=${{ vars.AWS_ACCOUNT_ID }}
-            AWS_PRIMARY_REGION=${{ vars.AWS_PRIMARY_REGION }}
-            AWS_GITHUB_ACTIONS_ROLE=${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
-            ENV=${{ matrix.environment }}
-          runCmd: |
-            echo $"\nVerifying AWS credentials..."
-            if ! aws sts get-caller-identity; then
-              echo "AWS authentication failed. Debug info:"
-              aws sts get-caller-identity --debug
-              exit 1
-            fi
-            echo "Successfully authenticated with AWS"
-            
-            if [ -z "$AWS_ACCOUNT_ID" ] || [ -z "$AWS_PRIMARY_REGION" ] || [ -z "$AWS_GITHUB_ACTIONS_ROLE" ]; then
-              echo "Failed to retrieve necessary AWS variables for $ENV environment"
-              return 1
-            fi
-            
-            echo $"\nDeploying to $ENV environment..."
-            chmod +x .github/scripts/sam-build-and-deploy-services.sh 
-            chmod +x .github/scripts/deploy-service-configuration.sh
+  # deploy-services:
+  #   runs-on: ubuntu-latest
+  #   needs: [check-changes, deploy-service-config]
+  #   if: needs.check-changes.outputs.code_changed  == 'true'
+  #   strategy:
+  #     matrix:
+  #       environment: [dev, staging]
+  #   environment: ${{ matrix.environment }}
+  #   steps:
+  #     - name: Check-out Code
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0  # Ensure full checkout
+      
+  #     - name: Configure AWS credentials
+  #       id: aws-creds
+  #       uses: aws-actions/configure-aws-credentials@v4
+  #       with:
+  #         role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
+  #         role-session-name: GithubWorkflow-Deployment-dev-staging
+  #         aws-region: ${{ vars.AWS_PRIMARY_REGION }}
+  #         output-credentials: true
+      
+  #     - name: Set-up Devcontainer Environment Variables
+  #       run: |
+  #         echo "PWD=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
+  #         cp .devcontainer/.env.ci .devcontainer/.env
+  #         echo ".devcontainer/.env:"
+  #         cat .devcontainer/.env
 
-            if ! .github/scripts/sam-build-and-deploy-services.sh $ENV $AWS_ACCOUNT_ID $AWS_PRIMARY_REGION false ; then
-              echo "Deployment failed for $ENV environment"
-              return 1
-            fi
-            echo "Deployment completed successfully for $ENV environment"
+  #     - name: Deploy Services to ${{ matrix.environment }}
+  #       uses: devcontainers/ci@v0.3
+  #       env:
+  #         GH_ACTIONS_PAT: ${{ secrets.GH_ACTIONS_PAT }}
+  #       with:
+  #         cacheFrom: ghcr.io/limorl/monorepo-python-sample-devcontainer
+  #         push: never
+  #         env: |
+  #           AWS_REGION=${{ vars.AWS_PRIMARY_REGION }}
+  #           AWS_ACCOUNT_ID=${{ vars.AWS_ACCOUNT_ID }}
+  #           AWS_PRIMARY_REGION=${{ vars.AWS_PRIMARY_REGION }}
+  #           AWS_GITHUB_ACTIONS_ROLE=${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
+  #           ENV=${{ matrix.environment }}
+  #         runCmd: |
+  #           echo $"\nVerifying AWS credentials..."
+  #           if ! aws sts get-caller-identity; then
+  #             echo "AWS authentication failed. Debug info:"
+  #             aws sts get-caller-identity --debug
+  #             exit 1
+  #           fi
+  #           echo "Successfully authenticated with AWS"
+            
+  #           if [ -z "$AWS_ACCOUNT_ID" ] || [ -z "$AWS_PRIMARY_REGION" ] || [ -z "$AWS_GITHUB_ACTIONS_ROLE" ]; then
+  #             echo "Failed to retrieve necessary AWS variables for $ENV environment"
+  #             return 1
+  #           fi
+            
+  #           echo $"\nDeploying to $ENV environment..."
+  #           chmod +x .github/scripts/sam-build-and-deploy-services.sh 
+  #           chmod +x .github/scripts/deploy-service-configuration.sh
+
+  #           if ! .github/scripts/sam-build-and-deploy-services.sh $ENV $AWS_ACCOUNT_ID $AWS_PRIMARY_REGION false ; then
+  #             echo "Deployment failed for $ENV environment"
+  #             return 1
+  #           fi
+  #           echo "Deployment completed successfully for $ENV environment"
