update credentials in devcontainer env when running integration tests

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -1,9 +1,8 @@
-name: Integration Tests - Staging
+name: Integration Tests against Staging
 on:
     schedule:
         - cron: '00 20 * * *' 
     workflow_dispatch:
-    workflow_call:
 
 jobs:
     test-integration:
@@ -15,6 +14,15 @@ jobs:
           uses: actions/checkout@v4
           with:
             fetch-depth: 0
+
+        - name: Configure AWS credentials
+          id: aws-creds
+          uses: aws-actions/configure-aws-credentials@v4
+          with:
+            role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
+            role-session-name: GithubWorkflow-Deployment-dev-staging
+            aws-region: ${{ vars.AWS_PRIMARY_REGION }}
+            output-credentials: true
     
         - name: Login to GitHub Container Registry
           uses: docker/login-action@v3
@@ -35,6 +43,14 @@ jobs:
           with:    
             cacheFrom: ghcr.io/limorl/monorepo-python-sample-devcontainer
             push: never
+            env: |
+                AWS_ACCESS_KEY_ID=${{ steps.aws-creds.outputs.aws-access-key-id }}
+                AWS_SECRET_ACCESS_KEY=${{ steps.aws-creds.outputs.aws-secret-access-key }}
+                AWS_SESSION_TOKEN=${{ steps.aws-creds.outputs.aws-session-token }}
+                AWS_REGION=${{ vars.AWS_PRIMARY_REGION }}
+                AWS_ACCOUNT_ID=${{ vars.AWS_ACCOUNT_ID }}
+                AWS_PRIMARY_REGION=${{ vars.AWS_PRIMARY_REGION }}
+                AWS_GITHUB_ACTIONS_ROLE=${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
             runCmd: |
                 set -e
                 echo $"\nRunning detect-secrets..."
@@ -51,6 +67,14 @@ jobs:
                 
                 echo $"\nRunning Unit tests..."
                 poetry run pytest -m "not integration and not e2e"
+
+                echo $"\nVerifying AWS credentials..."
+                if ! aws sts get-caller-identity; then
+                  echo "AWS authentication failed. Debug info:"
+                  aws sts get-caller-identity --debug
+                  exit 1
+                fi
+                echo "Successfully authenticated with AWS"
 
                 echo $"\nRunning Integration tests..."
                 poetry run pytest -m "integration and e2e"
